### ISSUE TITLE
Android keeps asking for USB device permission

### ISSUE THREAD

**Issue by haroon-ali** [green-green-avk/AnotherTermLite#2]
Hi,
On Android Oreo, It keeps asking every time I connect the device or connect to it using the app. Of course, I've choosen "use by default"
I think it's a manifest issue as it doesn't ask for USB permissions, maybe.

**Comment by green-green-avk** [comment]
Sorry, it's Android own behavior and it's by design. USB device permission is special and cannot be placed into the Manifest.
