### ISSUE TITLE
baudrate is not changed on $TERMSH serial BAUDRATE

### ISSUE THREAD

**Issue by haroon-ali** [green-green-avk/AnotherTermLite#3]
Hi,
Again thanks for this useful app.
I noticed that when I used the shell `$TERMSH serial 57600` for example, baudrate is not really changed.
I've rebuild the app and changed this line `private int baudrate = 9600;` in app/src/main/java/green_green_avk/anotherterm/backends/usbUart/UsbUartModule.java to `private int baudrate = 57600;` .. Now it's working fine at baudrate 57600.

**Comment by green-green-avk** [comment]
Sorry for so long delay.
Fixed by commit bfa2ca93c83239f7bec4b977c720e83cb90507c0.
Thank you for the report.
