### ISSUE TITLE
Best terminal emulator ever

### ISSUE THREAD

**Issue by mame82** [green-green-avk/AnotherTermLite#4]
Hi,

thanks for the great project. Before beeing pointed to it, I thought their is no terminal emu supporting:
- USB CDC ACM
- ANSI escape sequences for colors
- escape sequences for free cursor placement

Seems this is the first terminal which could deal with Nordic's CLI library from nRF5 SDK.

See here: https://twitter.com/mame82/status/1149753377078882314?s=19

Excuse the typos in the tweet, but I linked the app itself.

Where to find the paid version with SSH support?

**Comment by green-green-avk** [comment]
Sorry, I can't provide the exact date for the SSH version. To work it around, it's possible to build any Linux SSH client to use with the terminal emulator. Dropbear or something like it.

**Comment by green-green-avk** [comment]
Ready: https://github.com/green-green-avk/AnotherTerm
SSH is here.
